### ISSUE TITLE
Lack of documentation for visitor 

### ISSUE THREAD

**Issue by danielpetisme** [antlr/antlr4-javascript#37]
I would like to use a visitor instead of a listener for fo through the AST.
The [documentation](https://theantlrguy.atlassian.net/wiki/display/ANTLR4/JavaScript+Target) explains how to bootstrap a listener but not a visitor.

This is the generated visitor
```javascript
// jshint ignore: start
var antlr4 = require('antlr4/index');

// This class defines a complete generic visitor for a parse tree produced by MyParser.

function MyVisitor() {
  antlr4.tree.ParseTreeVisitor.call(this);
  return this;
}

MyVisitor.prototype = Object.create(antlr4.tree.ParseTreeVisitor.prototype);
MyVisitor.prototype.constructor = MyVisitor;

// Visit a parse tree produced by MyParser#myFirstRule.
MyVisitor.prototype.visitMyFirstRule = function(ctx) {
};

exports.MyVisitor = MyVisitor;
```
I tried the following snippet (a straightforward Java translation).
```javascript
var chars = new antlr4.InputStream(source);
var lexer = new MyLexer(chars);
var tokens = new antlr4.CommonTokenStream(lexer);
var parser = new MyParser(tokens);
var tree = parser.myFirstRule();
var myVisitor = new MyVisitor();
myVisitor.visit(tree);
```
but I get `TypeError: Object #<MyVisitor> has no method 'visit'`

I had a lool to the `antlr/tree/Tree.js`, I didn't see any `visit` method.

Could you documentate this part (or just point me to a resource I missed).

**Comment by azukaar** [comment]
+1 Same here
Please fix the doc ASAP because it's far too light... Even for using listener it just give a basic exemple, and it's just assumed that everything will work like described in the Java doc, but clearly it doesn't for many reasons. It has been a big waste of time to get things done the first time I used it as well. I'm not trying to be mean but it really grinded my gear, sorry guys.

By the way, if you were wondering, the issue about the lack of some methods have already been reported : https://github.com/antlr/antlr4-javascript/issues/23

Finally, to answer your question in a more practical way (I know it's been 3 week but still) :
You don't really need the visitor() methods to go thought your tree, simply call the generated methods, for exemple

    var chars = new antlr4.InputStream(source);
    var lexer = new MyLexer(chars);
    var tokens = new antlr4.CommonTokenStream(lexer);
    var parser = new MyParser(tokens);
    var tree = parser.myFirstRule();
    var myVisitor = new MyVisitor();
    myVisitor.visitMyFirstRule(tree);

Why ? Because the ctx arg of the function is supposed to be a RuleContext-like object which implements ParseTree. It will start going thought your tree.

PS : A temporary visit() function for you to use might kinda straightforwrd to do in JS actually, remember that every JS object have two way of defining litteral :

    myVisitor.prototype.visit = function(ctx) {
	    //Get the name of the node
	    var name = ctx.parser.ruleNames[ctx.ruleIndex];
	    //Sharpen the name of the function VisitNode()
	    var funcName = "visit" + name.charAt(0).toUpperCase() + name.slice(1)
	    //Call it
	    return this[funcName](ctx);
    }

This might give you a little boost but consider going further with this ! ;)

**Comment by ericvergnaud** [comment]
Guys,
I appreciate your input.
Please remember that nobody is getting paid to provide this.
I don't personally use visitors, happy to review any proposals.
Cheers

**Comment by krzkaczor** [comment]
@ericvergnaud are you accepting PR's improving readme to this repo? Probably I could improve with few examples and clear install notes etc.

**Comment by ericvergnaud** [comment]
Hi,
all the antlr repos have been merged, so you should post your PR on the antlr/antlr4 repo.
I will indeed review it and accept any improvement. Terence will bless them.
Eric
